# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79a2bc7686c4e61c06c47e418b631a966d1e797b010aff37b9b05e2eaa754d6e200c04f1a5989ed322685a3675740fdfef5c34070a3cfa2b488611045e58621f

test:
  secret_key_base: bee76d494111dfbca3438f1d9cd491c566e5412c0b125d3f86f8766a23ab182de38050b0d610a8126dc7be04bc391b0d7d0e69f6d059619b9bcd8e91afee2e33

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
